spring:
  application:
    name: bing-picture
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.228.210:3306/picture
    username: root
    password: 729158
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 2
  redis:
    host: 39.108.228.210
    port: 6379
    database: 0
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 80
